apiVersion: v1
kind: Pod
metadata:
  name: test-loader
spec:
    containers:
      - name: test-loader
        image: pgvector/pgvector:pg16
        volumeMounts:
          - mountPath: /models
            name: model-volume
        command: ["sleep", "3600"]
    volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
